### ISSUE TITLE
No feedback that an item was not added to the merchant's database

### ISSUE THREAD

**Issue by noahshaw11** [SCCapstone/EZBag#188]
When inputting random characters into the price and tax fields, it seems that the item is not being added to the database (as it shouldn't). However, no feedback is given to the user that the item could not be added to the database and why that is so.

https://user-images.githubusercontent.com/47468872/114334099-da108180-9b17-11eb-88fd-841d5ab3aba1.mp4

**Comment by cjshearer** [comment]
just fixed in 5ea1b11
