### ISSUE TITLE
Display list of products in merchant database

### ISSUE THREAD

**Issue by noahshaw11** [SCCapstone/EZBag#190]
I believe it would be a great idea to have a page that lists all the products in a merchant's database. This way merchants can view and delete products from their database.

**Comment by BrendanCReidy** [comment]
Business scanner view implements this functionality via search bar. I believe a list would be impractical for large databases, making a search bar the optimal way to go. Perhaps a combination of a list and search bar would be the most ideal solution, but functionally this already exists
